[package]
name = "assert_egraph"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
egg = "0.10.0"
itertools = "0.14.0"
nom = "8.0.0"
once_cell = "1.21.3"
winnow = "0.7.6"
